# Generated by Django 4.2 on 2026-01-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_videopost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
