# Generated by Django 4.2 on 2026-01-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videopost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
