# Generated by Django 4.2 on 2026-01-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopost',
            old_name='views_count',
            new_name='views',
        ),
    ]
