# Generated by Django 4.2 on 2026-01-11 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_rename_views_count_videopost_views'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
